// Assignment_08/src/app/components/PokemonCard.jsx
import React, { PropTypes } from 'react';

const PokemonCard = ({ pokemon, onPinToFavorites, onUnpinFromFavorites }) => (
  <div
    key={pokemon.id}
    className={'pockemon-card'.concat(pokemon.favorite ? ' pockemon-card--favorite' : '')}
  >
    <div
      className="pockemon-card__image"
      style={{ backgroundImage: `url(${pokemon.image})` }}
      title={`Pokemon ${pokemon.name}`}
    >
      <div className="pockemon-card__id">
        #{'0'.repeat(3 - pokemon.id.toString().length).concat(pokemon.id.toString())}
      </div>
      <div className="pockemon-card__image-fav">
        <i className="material-icons">favorite_border</i>
      </div>
    </div>
    <h2 className="pockemon-card__name">{pokemon.name}</h2>
    <div className="pockemon-card__abilities">
      {pokemon.types.map((type, index) => (
        <div
          key={index}
          className={'pockemon-card__type '.concat('pockemon-card__type--'.concat(type))}
        >
          {type}
        </div>
      ))}
    </div>
    <div className="pockemon-card__action-wrapper">
      <button
        className="pockemon-card__btn pockemon-card__btn--add"
        onClick={() => onPinToFavorites(pokemon)}
      >
        Add to favorites
      </button>
      <button
        className="pockemon-card__btn pockemon-card__btn--rm"
        onClick={() => onUnpinFromFavorites(pokemon)}
      >
        Remove from favorites
      </button>
    </div>
  </div>
);

PokemonCard.propTypes = {
  pokemon: PropTypes.shape({
    id: PropTypes.number.isRequired,
    name: PropTypes.string.isRequired,
    types: PropTypes.arrayOf(PropTypes.string).isRequired,
    image: PropTypes.string.isRequired,
    favorite: PropTypes.bool,
  }).isRequired,
  onPinToFavorites: PropTypes.func,
  onUnpinFromFavorites: PropTypes.func,
};

export default PokemonCard;

// Assignment_09/src/app/pokemon-card/pokemon-card.component.ts
import {Component, OnInit, Input, Output, EventEmitter, Renderer, ElementRef} from '@angular/core';
import {Router} from "@angular/router";

import { Pokemon } from '../shared/Pokemon';
import {State} from "../shared/State";

@Component({
  selector: 'pokemon-card',
  templateUrl: './pokemon-card.component.html',
  styleUrls: ['./pokemon-card.component.scss']
})
export class PokemonCardComponent {
  @Input() pokemon: Pokemon;
  @Input() state: State;

  @Output() onFavorites = new EventEmitter<Pokemon>();

  constructor(private router: Router, private renderer: Renderer, private elementRef: ElementRef) {}

  ngOnInit() {
    if (this.state.currentPokeId === this.pokemon.id) {
      this.renderer.invokeElementMethod(this.elementRef.nativeElement, 'scrollIntoView', [true]);
    }
  }

  onFavoritesClick(pokemon: Pokemon) {
    this.onFavorites.emit(pokemon);
  }

  onDetailsClick(pokemon: Pokemon) {
    this.router.navigate(['/pokemon', pokemon.id, this.state ]);
  }

}

<div class="pockemon-card" [class.pockemon-card--favorite]="pokemon.favorite" [id]="pokemon.name" >
  <div class="pockemon-card__image" [ngStyle]="{'background-image': 'url(' + pokemon.image + ')'}">
    <div class="pockemon-card__id">
      #{{'0'.repeat(3 - pokemon.id.toString().length).concat(pokemon.id.toString())}}
    </div>
    <div class="pockemon-card__image-fav">
      <i class="material-icons">star_border</i>
    </div>
  </div>
  <h2 class="pockemon-card__name">{{pokemon.name}}</h2>
  <div class="pockemon-card__abilities">
    <div
      [ngClass]="'pockemon-card__type '.concat('pockemon-card__type--'.concat(type))"
      *ngFor="let type of pokemon.types"
    >{{type}}</div>
  </div>
  <div class="pockemon-card__controls">
    <button class="pockemon-card__btn"
            (click)="onDetailsClick(pokemon)"
            titlte="Pokemon's details"
    >
      Details
    </button>
    <button *ngIf="!pokemon.favorite"
            (click)="onFavoritesClick(pokemon)"
            class="pockemon-card__btn pockemon-card__btn--add"
            title="Add to favorites"
    >
      <i class="material-icons">favorite</i>
    </button>
    <button *ngIf="pokemon.favorite"
            (click)="onFavoritesClick(pokemon)"
            class="pockemon-card__btn pockemon-card__btn--rm"
            title="Remove from favorites"
    >
      <i class="material-icons">clear</i>
    </button>
  </div>
</div>
